astor==0.8.1
certifi==2021.5.30
charset-normalizer==2.0.3
cycler==0.10.0
decorator==4.4.2
gast==0.5.1
idna==3.2
imageio==2.9.0
joblib==1.0.1
kiwisolver==1.3.1
matplotlib==3.4.2
networkx==2.6.2
numpy==1.21.1
paddlepaddle-gpu==2.1.1.post112
pandas==1.3.1
Pillow==8.3.1
protobuf==3.17.3
pyparsing==2.4.7
python-dateutil==2.8.2
pytz==2021.1
PyWavelets==1.1.1
requests==2.26.0
scikit-image==0.18.2
scikit-learn==0.24.2
scipy==1.7.0
six==1.16.0
sklearn==0.0
threadpoolctl==2.2.0
tifffile==0.15.1
tqdm==4.61.2
urllib3==1.26.6
